Lesson 15 home work
azanorth/just_notes pull request #6
Opened 2023-11-02 18:43 UTC by azanorth

- Rewrited the whole logic to use the Bloc state management
- Implemented the HydratedStorage
Tried to use different approaches to state management with the Bloc library

The main logic of this sample still is the same

![Записування 2023-11-02 203754](https://github.com/azanorth/just_notes/assets/26149983/bc4a6769-2c75-4af0-b642-2b3075e2c450)

2023-11-05 10:51 UTC, VadymPinchuk requested changes

2023-11-05 10:51 UTC, VadymPinchuk commented on lib/home_work/lesson_15/feature/task_item/bloc/task_item_bloc.dart
якось дуже гранульовано. на кожну таску є свій блок? це не дуже функціонально

2023-11-05 10:51 UTC, VadymPinchuk commented on lib/home_work/lesson_15/presentation/widgets/list_item.dart
> +                  state.isMarked
context.read<TaskItemBloc>().add( 
state.isMarked ? const TaskItemEvent.unMark() : const TaskItemEvent.mark(),
)

2023-11-05 10:51 UTC, VadymPinchuk commented on lib/home_work/lesson_15/presentation/widgets/list_item.dart
> +            value: _item.status == Status.completed ? true : false,
value: _item.status == Status.completed,

2023-11-05 10:51 UTC, VadymPinchuk commented on lib/home_work/lesson_15/presentation/widgets/task_list.dart
> +                child: BlocProvider(
занадто гранульовано.

2023-11-05 10:58 UTC, VadymPinchuk requested changes

2023-11-05 10:58 UTC, VadymPinchuk commented on lib/home_work/lesson_15/presentation/widgets/list_item.dart
> +                  TaskListEvent.changed(
навіщо нам TaskItemBloc якщо з кожного елементу ми викликаємо TaskListEvent.changed() і відповідно ListBloc реагує на ці події

2023-11-05 10:58 UTC, VadymPinchuk commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    emit(const TaskListState.loading());
Ось і лоадер який змінює весь екран а потім малює весь список заново уже із зміненим елементом

2023-11-05 10:58 UTC, VadymPinchuk commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    await _readTasks(emit);
чи є сенс знову вичитувати весь список?

2023-11-05 10:58 UTC, VadymPinchuk commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    emit(const TaskListState.loading());
також зайвий

2023-11-05 10:58 UTC, VadymPinchuk commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    emit(const TaskListState.loading());
як і тут )

2023-11-06 11:22 UTC, azanorth commented on lib/home_work/lesson_15/feature/task_item/bloc/task_item_bloc.dart
Agree, fixed thanks

2023-11-06 11:22 UTC, azanorth commented on lib/home_work/lesson_15/presentation/widgets/list_item.dart
> +                  state.isMarked
Fixed, no longer needed

2023-11-06 11:22 UTC, azanorth commented on lib/home_work/lesson_15/presentation/widgets/list_item.dart
> +            value: _item.status == Status.completed ? true : false,
Nice, thanks fixed

2023-11-06 11:22 UTC, azanorth commented on lib/home_work/lesson_15/presentation/widgets/task_list.dart
> +                child: BlocProvider(
Agree, fixed

2023-11-06 11:23 UTC, azanorth commented on lib/home_work/lesson_15/presentation/widgets/list_item.dart
> +                  TaskListEvent.changed(
Fixed

2023-11-06 11:23 UTC, azanorth commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    emit(const TaskListState.loading());
Fixed

2023-11-06 11:23 UTC, azanorth commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    await _readTasks(emit);
Agree, there is no reason, fixed

2023-11-06 11:23 UTC, azanorth commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    emit(const TaskListState.loading());
Fixed

2023-11-06 11:23 UTC, azanorth commented on lib/home_work/lesson_15/feature/task_list/bloc/task_list_bloc.dart
> +    emit(const TaskListState.loading());
Fixed

2023-11-07 19:15 UTC, merged